/** 
 * Names: Daniel Watson, Echo Salonga, Daniel Tollis
 * Date: June 26, 2026
 * Description:
 * - This file is the base layout for our Student Portal.
 * - Wraps all pages with a nav bar, footer, and global fonts/styles.
 * 
 * Inputs:
 * - Receives React children, this is the page content that Next.js applies.
 * - Uses imported global styles, fonts, and components (such as the NavBar & Footer).
 * 
 * Processing:
 * - Applies the global fonts and styles to the entirety of the application.
 * - Wraps every page with proper structure.
 * 
 * Outputs:
 * - Returns the complete webpage layout for every page (html, body, etc.)
*/

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/SchoolNavBar";
import Footer from "./components/SchoolFooter";

// Font Styling //
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Page Metadata //
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout //
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <NavBar/>
        
        {children}
        
        <Footer/>
      </body>
    </html>
  );
}
